[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
  "@openzeppelin/=lib/openzeppelin-contracts/"
]

# Allow writing to deployment.json in the root directory
fs_permissions = [
  { access = "write", path = "./deployment.json" },
  { access = "write", path = "./deployments" }
]